.TH DCP "1" "July 2012" "dcp 0.1" "Distributed File Copy Tool"

.SH "NAME"
dcp \- copy file(s) in parallel on a distributed system.

.SH "SYNOPSIS"

\fBdcp\fR [\fICdfhpRrv\fR] [\fI--\fR] source_file target_file
.br
\fBdcp\fR [\fICdfhpRrv\fR] [\fI--\fR] source_file ... target_directory

.SH "DESCRIPTION"
\fBdcp\fR is a file copy tool in the spirit of \fBcp\fR(1) that evenly distributes work across a large cluster without centralized state. It is designed for copying files which are located on a distributed parallel file system. The method used in the file copy process is a self-stabilization algorithm which enables per-node autonomous processing and a token passing scheme to detect termination (see \fIhttp://doi.acm.org/10.1145/2388996.2389114\fR for more information).

dcp requires an MPI environment (such as OpenMPI's \fBmpirun\fR(1)).

.SH "OPTIONS"

.TP
\fB-C\fR, \fB\-\-skip-compare\fR
Skip the compare operation to confirm file integrity. When using this option, a file integrity check, such as md5sum, should be performed after the file(s) have been copied.

.TP
\fB\-d <level>\fR, \fB\-\-debug=<level>\fR
Specify the level of debug information to output. Level may be one of: 'fatal', 'err', 'warn', 'info', or 'dbg'. Increasingly verbose debug levels include the output of less verbose debug levels.

.TP
\fB\-f\fR, \fB\-\-force\fR
Remove existing destination files if creation or truncation fails.

.TP
\fB\-h\fR, \fB\-\-help\fR
Print a brief message listing the \fBdcp\fR options and usage.

.TP
\fB\-p\fR, \fB\-\-preserve\fR
Preserve the original files' owner, group, permissions (including the setuid and setgid bits), time of last modification and time of last access. In case duplication of owner or group fails, the setuid and setgid bits are cleared.

.TP
\fB\-R\fR, \fB\-\-recursive\fR
Copy directories recursively, and do the right thing when objects other than ordinary files or directories are encountered.

.TP
\fB\-r\fR, \fB\-\-recursive-unspecified\fR
Copy directories recursively, and ignore objects other than ordinary files or directories.

.TP
\fB\-v\fR, \fB\-\-version\fR
Print version information and exit.

.SH "COPYING"
Copyright (C) 2011-2012 Los Alamos National Security.

.SH "AUTHORS"
Jharrod LaFon <jlafon@lanl.gov>
.br
Jon Bringhurst <jonb@lanl.gov>
