.TH DCP "1" "March 2012" "dcp 0.1" "Distributed File Copy Tool"

.SH "NAME"
dcp \- copy a file in parallel on a distributed system.

.SH "SYNOPSIS"
\fBdcp\fR [\fI-hVv\fR] [\fI-d <level>\fR] <source> ... [<special>:]<destination>

.SH "DESCRIPTION"
\fBdcp\fR is a file and directory copy tool that evenly distributes work
across a large cluster without centralized state. It is designed for copying
files which are located on a parallel file system (such as Lustre or PanFS).

.SH "OPTIONS"

.TP
\fB\-d <level>\fR, \fB\-\-debug=<level>\fR
Specify the level of debug information to output.

.TP
\fB\-h\fR, \fB\-\-help\fR
Print a brief message listing the \fBdcp\fR options and usage.

.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information and exit.

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose logging messages.

.SH "FIELDS"

.TP
\fBsource\fR
The path of the source to be used in the copy operation. The source may be
a directory or file object.

.TP
\fBdestination\fR
The path of the destination to be used in the copy operation. If the
destination is a file, it will be overwritten by the source file. If the
destination is a directory, the source file(s) will be copied into the
specified directory

.TP
\fBspecial\fR
For future use. Currently unimplemented.

.SH "EXAMPLES"
.eo
Copy a single file from a source to a destination file:
.nf
> dcp from.txt to.txt
.fi
.ec

.eo
Copy two files destination directory:
.nf
> dcp from1.txt from2.txt my_dir
.fi
.ec

.SH "COPYING"
Copyright (C) 2011-2012 Los Alamos National Security.

.SH "AUTHORS"
Jharrod LaFon <jlafon@lanl.gov>
.br
Jon Bringhurst <jonb@lanl.gov>
